conductor-oss/python-sdk

src/conductor/client/http/api_client.py
Changes:
- Removed unused methods from HTTP API client
- Added `gzip` encoding for all requests sent to Conductor server
Tests:
- Received header at response from server that supports `gzip`:
- `header: Content-Encoding: gzip`
- Same behavior with server without `gzip` support
=> Update http api client

src/conductor/client/http/api_client.py, tests/integration.py, tests/unit/test_configuration.py
This PR simplies replicates how module requests deals with authenticated URLs.
One option is to mege https://github.com/conductor-sdk/conductor-python/pull/118  and then rebase and run integration testes against a basic auth URL server.
=> Allow using basic auth URL

.github/workflows/release.yml
* Previously, many events were triggering CI workflow, trying to re-publish the same release
* Added a sleep for `30` seconds before attempting to validate the new release from `pypi`
=> Fixed issues related to CI GH workflow

src/conductor/client/automator/task_runner.py, src/conductor/client/worker/worker_interface.py
paused() interface give an opportunity to the worker/client to check whether to poll tasks to execute. #134
=> Added support for paused workers

src/conductor/client/http/api/workflow_bulk_resource_api.py, src/conductor/client/http/api/workflow_resource_api.py, src/conductor/client/workflow/executor/workflow_executor.py, tests/integration/workflow/test_workflow_execution.py
Add optional boolean triggerFailureWorkflow parameter to trigger failure workflow upon termination
=> orkes-conductor-957: update Terminate API

src/conductor/client/http/api_client.py
This PR fixes an unexpected behaviour when polling for tasks on an empty task queue observed with conductor-python version 1.0.56
In [ApiClient.deserialize](https://github.com/conductor-sdk/conductor-python/blob/8204fed72935ff92a320b19ef6d3ece604755ad7/src/conductor/client/http/api_client.py#L199) method, the following code is executed:
```
try:
data = response.resp.json()
except Exception:
data = response.resp.text
```
When there is no task to be fetched, the exception is raised and data variable will be an empty string `data = ''`. After that, [ApiClient.__deserialize](https://github.com/conductor-sdk/conductor-python/blob/8204fed72935ff92a320b19ef6d3ece604755ad7/src/conductor/client/http/api_client.py#L221) method is called, were this check is performed:
```
if data is b'' or data is …
```
=> :bug: Fixes no content response on task poll

src/conductor/client/automator/task_runner.py, tests/unit/test_task_runner.py
Add logs to the task result and change the log message from info to error in case of an exception during the task execution.
=> add logs to the task result

setup.cfg, src/conductor/client/workflow/conductor_workflow.py, src/conductor/client/workflow/task/fork_task.py, tests/integration/metadata/test_workflow_definition.py
Added support for fork join tasks using rshift >> operator.
E.g
```python
uri = "https://orkes-api-tester.orkesconductor.com/get"
forked_task_1 = HttpTask("http_task_1", HttpInput(uri))
forked_task_2 = HttpTask("http_task_2", HttpInput(uri))
forked_task_31 = HttpTask("http_task_31", HttpInput(uri))
forked_task_32 = HttpTask("http_task_32", HttpInput(uri))
forked_task_41 = HttpTask("http_task_41", HttpInput(uri))
forked_task_42 = HttpTask("http_task_42", HttpInput(uri))
// Forks two tasks
workflow >> [forked_task_1, forked_task_2]
// Forks two sequences of tasks
workflow >> [[forked_task_31, forked_task_32], [forked_task_41, forked_task_42]]
```
=> Added fork join to rshift

README.md
Was fairly annoying to track down the right imports for getting at minimal configuration setup in a fast onboarding manner - simply adding the import to cleanup onboarding for folks.
=> Add missing import for easier onboarding.

src/conductor/client/workflow/task/do_while_task.py, tests/integration/metadata/test_workflow_definition.py
Hello,
An exception is raised when adding a DoWhileTask or a LoopTask that contains a list of `tasks` to a workflow.
```python
workflow = ConductorWorkflow(...)
task1 = SimpleTask(...)
task2 = SimpleTask(...)
dowhile_single = DoWhileTask(
task_ref_name='dowhile_single',
termination_condition="$.dowhile_single['iteration'] < 2",
tasks = task1
)
workflow.add(dowhile_single)
dowhile_multiple = DoWhileTask(
task_ref_name='dowhile_multiple',
termination_condition="$.dowhile_multiple['iteration'] < 2",
tasks = [ task1, task2 ]
)
workflow.add(dowhile_multiple)
``` 
It seems this bug has been introduced along this commit @gardusig https://github.com/conductor-sdk/conductor-python/commit/5b5bf04a5408b799111fc071b7fb62fa2104ac80#diff-6561dd5f4d67f7b315998c89eafc7cee302c3c76e800ee8538b9f7b0594cffdeR9 …
=> Fix DoWhileTask/LoopTask with several subtasks

src/conductor/client/automator/task_handler.py, src/conductor/client/automator/task_runner.py, src/conductor/client/worker/worker_interface.py, src/conductor/client/workflow/conductor_workflow.py, src/conductor/client/workflow/task/do_while_task.py, tests/integration/metadata/test_workflow_definition.py, tests/integration/workflow/test_workflow_execution.py, tests/unit/automator/test_task_runner.py
Allow sharing task definitions amongst a worker process in order to conserve memory: #219 
Fix DoWhileTask/LoopTask with several subtasks: #220
=> Fix do while task list and prototype shared tasks

docs/worker/README.md, src/conductor/client/automator/task_handler.py, src/conductor/client/automator/task_runner.py, src/conductor/client/worker/worker.py, src/conductor/client/worker/worker_interface.py, tests/integration/main.py, tests/integration/resources/worker/python/python_worker.py, tests/integration/workflow/test_workflow_execution.py, tests/unit/automator/test_task_handler.py, tests/unit/automator/test_task_runner.py, tests/unit/resources/workers.py
Added support to read an worker.ini file in the root directory of the worker code that allows for setting default values for task domain and polling intervals for workers. Config file will always override constructor params. These properties are expected to be in the form of: 
```
[task_definition_name]
domain = <domain>
polling_interval = <polling-interval-in-ms>
[DEFAULT]
domain = <domain>
polling_interval = <polling-interval-in-ms>
```
Examples:
```
[DEFAULT]
domain = nice
polling_interval = 2000
[python_annotated_task_1]
domain = cool
polling_interval = 500
[python_annotated_task_2]
domain = hot
polling_interval = 300
```
Workers can also be configured at run time by using environment variables which override configuration files as well. Environment variables will always override …
=> Added domain and polling_interval in config and env vars for worker tasks

src/conductor/client/http/models/state_change_event.py, src/conductor/client/http/models/workflow_task.py
Fixes this error that happens in versions less than 3.11
```
from conductor.client.workflow.task.http_task import HttpTask, HttpInput
File "/usr/local/lib/python3.9/site-packages/conductor/client/workflow/task/http_task.py", line 7, in <module>
from conductor.client.workflow.task.task import TaskInterface
File "/usr/local/lib/python3.9/site-packages/conductor/client/workflow/task/task.py", line 7, in <module>
from conductor.client.http.models.workflow_task import WorkflowTask
File "/usr/local/lib/python3.9/site-packages/conductor/client/http/models/__init__.py", line 34, in <module>
from conductor.client.http.models.workflow_task import WorkflowTask
File "/usr/local/lib/python3.9/site-packages/conductor/client/http/models/workflow_task.py", line 3, in <module>
from typing import List, …
```
=> Fixed typing error for > Python 3.11

src/conductor/client/workflow/task/dynamic_fork_task.py, src/conductor/client/workflow/task/task.py, tests/integration/metadata/test_workflow_definition.py
The `DynamicForkTask` in its current state is non-functional. It requires a "pre_fork_task" and the dynamic tasks and their inputs are supposed to be taken from its output.
It's not working and it's too rigid. It won't allow using an INLINE task (given how this task outputs the result), it won't allow setting the dynamic tasks and inputs in the task def itself, or take it from a workflow input.
**TODO** (in an upcoming PR)
- When creating tasks it's just using task ref name. Task name should also be an option.  
- Tests + refactoring.
**NOTES** 
- I've tested this with this [code](https://gist.github.com/jmigueprieto/3ad5153eef2f92cb86d2cc5fe788525a) and generated the correct workflow.
=> FIX - Dynamic Fork (workflow as code) 

src/conductor/client/http/api_client.py, tests/unit/api_client/test_api_client.py
Fix serialization of UUID (and others) by falling back to string representation.
Reported in Slack: https://orkes-conductor.slack.com/archives/C02UQ3GNVBL/p1737637408509809
**NOTES**
The returned string is put into the `"result"` of a JSON object.  E.g.:
```json
{
"result": "49d57e8e-4b7c-4142-a59a-7b04432e0c52"
}
```
=> Fix worker output serialization issues

tests/unit/api_client/test_api_client.py
Minor follow-up of https://github.com/conductor-sdk/conductor-python/pull/275. I just realized the class name is wrong (was caught copy-pasting).
=> Fix wrong test class name

Dockerfile
Use python3.11-alpine as base for publishing to fix this issue https://github.com/conductor-sdk/conductor-python/actions/runs/13640732725/job/38129984990
=> Fix release GH Workflow

tests/integration/client/orkes/test_orkes_clients.py
A small change in the backend in a human readable error message is causing a test to fail
=> Fix failing test

.github/workflows/pull_request.yml, poetry.lock, pyproject.toml, src/conductor/asyncio_client/adapters/models/integration_adapter.py, src/conductor/asyncio_client/adapters/models/integration_def_adapter.py, src/conductor/asyncio_client/adapters/models/integration_def_form_field_adapter.py, src/conductor/asyncio_client/event/event_client.py, src/conductor/client/adapters/api_client_adapter.py, src/conductor/client/adapters/models/integration_adapter.py, src/conductor/client/adapters/models/integration_def_adapter.py, src/conductor/client/adapters/models/integration_def_form_field_adapter.py, src/conductor/client/adapters/models/integration_update_adapter.py, src/conductor/client/adapters/rest_adapter.py, src/conductor/client/orkes/orkes_task_client.py, tests/integration/async/test_async_orkes_authorization_client_integration.py, tests/integration/async/test_async_orkes_task_client_integration.py, tests/integration/async/test_async_orkes_workflow_client_integration.py, tests/integration/test_conductor_oss_workflow_integration.py, tests/integration/test_orkes_authorization_client_integration.py, tests/integration/test_orkes_integration_client_integration.py, tests/integration/test_orkes_metadata_client_integration.py, tests/integration/test_orkes_prompt_client_integration.py, tests/integration/test_orkes_scheduler_client_integration.py, tests/integration/test_orkes_schema_client_integration.py, tests/integration/test_orkes_secret_client_integration.py, tests/integration/test_orkes_service_registry_client_integration.py, tests/integration/test_orkes_task_client_integration.py, tests/integration/test_orkes_workflow_client_integration.py, tests/unit/orkes/test_task_client.py
Changes:
1. Updated check test results CI step to include integration tests
2. Updated IntegrationDef adapters for both sync and async client to include `CLOUD` category option
3. Updated IntegrationDefFormFieldAdapter to include `organizationId` field_name
Reason:
1. Сheck results step did not include verification of the completion of integration tests, so CI did not fail in the event of integration tests failing
2-3. Test cluster has been updated to version 5.2.20, which includes a new `CLOUD` category and a new field `organizationId`. Due to the absence of these values in the SDK, the tests failed.
=> Added sync and async integration tests to fail condition

poetry.lock, pyproject.toml
Changes:
* Removed limitation for python 3.13 in pyproject.toml
Reason:
* Keep backward compatibility with previous package versions
* Enable forward compatibility with Python 3.13+. The <3.13 restriction was overly conservative and all dependencies support Python 3.13.
=> Updated pyproject toml to remove py3.13 limitation
